const {contextBridge,ipcRenderer,webFrame}=require('electron');

contextBridge.exposeInMainWorld('desktopApi',{
  platform:process.platform,
  showAppMenu:(label)=>ipcRenderer.invoke('shell:showMenu',label),
  setTitleBarTheme:(theme)=>ipcRenderer.invoke('shell:setTitleBarTheme',theme),
  rendererZoomFactor:()=>webFrame.getZoomFactor(),
  getStatus:()=>ipcRenderer.invoke('bridge:getStatus'),
  scanProviders:()=>ipcRenderer.invoke('bridge:scanProviders'),
  sendPrompt:(m)=>ipcRenderer.invoke('bridge:sendPrompt',m),
  cancelPrompt:(id)=>ipcRenderer.invoke('bridge:cancelPrompt',id),
  startWorkTask:(payload)=>ipcRenderer.invoke('work:start',payload),
  stopWorkTask:(id)=>ipcRenderer.invoke('work:stop',id),
  resolveWorkApproval:(payload)=>ipcRenderer.invoke('work:resolveApproval',payload),
  chooseRepository:()=>ipcRenderer.invoke('repository:choose'),
  repositorySummary:(root)=>ipcRenderer.invoke('repository:summary',root),
  chooseLocalFolder:()=>ipcRenderer.invoke('files:chooseFolder'),
  localFolderSummary:(root)=>ipcRenderer.invoke('files:folderSummary',root),
  configureRelay:(c)=>ipcRenderer.invoke('bridge:configureRelay',c),
  listApiConnections:()=>ipcRenderer.invoke('api:listConnections'),
  addApiConnection:(c)=>ipcRenderer.invoke('api:addConnection',c),
  removeApiConnection:(id)=>ipcRenderer.invoke('api:removeConnection',id),
  listMcpConnections:()=>ipcRenderer.invoke('mcp:listConnections'),
  addMcpConnection:(c)=>ipcRenderer.invoke('mcp:addConnection',c),
  removeMcpConnection:(id)=>ipcRenderer.invoke('mcp:removeConnection',id),
  refreshMcpConnection:(id)=>ipcRenderer.invoke('mcp:refreshConnection',id),
  refreshAllMcpConnections:()=>ipcRenderer.invoke('mcp:refreshAll'),
  captureScreens:()=>ipcRenderer.invoke('computer:captureScreens'),
  startSystemDictation:()=>ipcRenderer.invoke('dictation:start'),
  computerPerformAction:(payload)=>ipcRenderer.invoke('computer:performAction',payload),
  computerClick:(payload)=>ipcRenderer.invoke('computer:click',payload),
  computerClickAndType:(payload)=>ipcRenderer.invoke('computer:clickAndType',payload),
  browserOpen:(payload)=>ipcRenderer.invoke('browser:open',payload),
  browserNewTab:(url)=>ipcRenderer.invoke('browser:newTab',url),
  browserSelectTab:(id)=>ipcRenderer.invoke('browser:selectTab',id),
  browserCloseTab:(id)=>ipcRenderer.invoke('browser:closeTab',id),
  browserSetSiteToolsEnabled:(value)=>ipcRenderer.invoke('browser:setSiteToolsEnabled',value),
  browserClearData:()=>ipcRenderer.invoke('browser:clearData'),
  browserCancelDownload:(id)=>ipcRenderer.invoke('browser:cancelDownload',id),
  browserOpenDownload:(id)=>ipcRenderer.invoke('browser:openDownload',id),
  browserShowDownload:(id)=>ipcRenderer.invoke('browser:showDownload',id),
  browserResolvePermission:(payload)=>ipcRenderer.invoke('browser:resolvePermission',payload),
  browserDismissError:()=>ipcRenderer.invoke('browser:dismissError'),
  browserOpenExternalProtocol:(url)=>ipcRenderer.invoke('browser:openExternalProtocol',url),
  browserStartAnnotation:()=>ipcRenderer.invoke('browser:startAnnotation'),
  browserCancelAnnotation:()=>ipcRenderer.invoke('browser:cancelAnnotation'),
  browserRefreshSiteTools:()=>ipcRenderer.invoke('browser:refreshSiteTools'),
  browserExecuteSiteTool:(payload)=>ipcRenderer.invoke('browser:executeSiteTool',payload),
  browserNavigate:(url)=>ipcRenderer.invoke('browser:navigate',url),
  browserSetBounds:(bounds)=>ipcRenderer.invoke('browser:setBounds',bounds),
  browserBack:()=>ipcRenderer.invoke('browser:back'),
  browserForward:()=>ipcRenderer.invoke('browser:forward'),
  browserReload:()=>ipcRenderer.invoke('browser:reload'),
  browserClose:()=>ipcRenderer.invoke('browser:close'),
  browserUseBuiltInSnapshot:(tabId)=>ipcRenderer.invoke('browserUse:builtInSnapshot',tabId),
  browserUseBuiltInAction:(payload)=>ipcRenderer.invoke('browserUse:builtInAction',payload),
  extensionBrowserListTabs:()=>ipcRenderer.invoke('browserUse:extensionListTabs'),
  extensionBrowserActivateTab:(tabId)=>ipcRenderer.invoke('browserUse:extensionActivateTab',tabId),
  extensionBrowserCreateTab:(payload)=>ipcRenderer.invoke('browserUse:extensionCreateTab',payload),
  extensionBrowserCloseTab:(tabId)=>ipcRenderer.invoke('browserUse:extensionCloseTab',tabId),
  extensionBrowserNavigate:(payload)=>ipcRenderer.invoke('browserUse:extensionNavigate',payload),
  extensionBrowserSnapshot:(tabId)=>ipcRenderer.invoke('browserUse:extensionSnapshot',tabId),
  extensionBrowserAction:(payload)=>ipcRenderer.invoke('browserUse:extensionAction',payload),
  openAuthUrl:(url)=>ipcRenderer.invoke('auth:openExternal',url),
  onPromptStream:(cb)=>{
    const h=(_e,event)=>cb(event);
    ipcRenderer.on('prompt-stream',h);
    return()=>ipcRenderer.removeListener('prompt-stream',h);
  },
  onWorkTask:(cb)=>{
    const h=(_e,state)=>cb(state);
    ipcRenderer.on('work-task',h);
    return()=>ipcRenderer.removeListener('work-task',h);
  },
  onBrowserState:(cb)=>{
    const h=(_e,state)=>cb(state);
    ipcRenderer.on('browser-state',h);
    return()=>ipcRenderer.removeListener('browser-state',h);
  },
  onAppCommand:(cb)=>{
    const h=(_e,command)=>cb(command);
    ipcRenderer.on('app-command',h);
    return()=>ipcRenderer.removeListener('app-command',h);
  },
  onAuthCallback:(cb)=>{
    const h=(_e,url)=>cb(url);
    ipcRenderer.on('auth-callback',h);
    return()=>ipcRenderer.removeListener('auth-callback',h);
  },
  onStatus:(cb)=>{
    const h=(_e,s)=>cb(s);
    ipcRenderer.on('bridge-status',h);
    return()=>ipcRenderer.removeListener('bridge-status',h);
  }
});
