import fs from'node:fs/promises';import os from'node:os';import path from'node:path';import http from'node:http';import{test,expect,_electron as E}from'@playwright/test';
const O=path.resolve('artifacts/linux-audit');await fs.mkdir(O,{recursive:true});const shot=(p,n)=>p.screenshot({path:path.join(O,n+'.png')});
function rec(){const r=[];return{r,add:(n,s,d='')=>{r.push({name:n,status:s,detail:d});console.log(s,n,d)},save:n=>fs.writeFile(path.join(O,n),JSON.stringify(r,null,2))}}
async function api(){const qs=[];const s=http.createServer(async(q,r)=>{if(q.url==='/v1/chat/completions'){let b=[];for await(const c of q)b.push(c);try{qs.push(JSON.parse(Buffer.concat(b)))}catch{};r.writeHead(200,{'content-type':'application/json'});return r.end(JSON.stringify({choices:[{message:{content:'Linux local QA response'}}]}))}r.writeHead(200,{'content-type':'text/html'});r.end('<title>Linux Browser QA</title><h1>Linux Browser QA</h1>')});await new Promise((a,b)=>{s.once('error',b);s.listen(0,'127.0.0.1',a)});return{s,qs,u:'http://127.0.0.1:'+s.address().port}}
test('packaged AppImage smoke',async()=>{const R=rec(),e=process.env.FREEAI_LINUX_EXECUTABLE,d=await fs.mkdtemp(path.join(os.tmpdir(),'fai-pkg-'));let a,p;try{a=await E.launch({executablePath:e,args:[`--user-data-dir=${d}`,'--no-sandbox']});p=await a.firstWindow();await p.waitForLoadState('domcontentloaded');await p.waitForTimeout(900);const x=await p.evaluate(async()=>({platform:window.desktopApi?.platform,info:await window.desktopApi?.getAppInfo?.()}));R.add('Packaged platform Linux',x.platform==='linux'?'PASS':'FAIL',x.platform);R.add('Packaged=true',x.info?.packaged?'PASS':'FAIL',JSON.stringify(x.info));R.add('Packaged window renders',(await p.locator('.authScreen,.desktopShell').count())>0?'PASS':'FAIL');await shot(p,'01-packaged')}finally{await R.save('packaged-results.json');await a?.close();await fs.rm(d,{recursive:true,force:true})}expect(R.r.filter(x=>x.status==='FAIL')).toEqual([])});
test('Linux shell full audit',async()=>{const{u,s,qs}=await api(),R=rec(),d=await fs.mkdtemp(path.join(os.tmpdir(),'fai-linux-'));let a,p;const errs=[];const C=async(n,f)=>{try{R.add(n,'PASS',await f()||'')}catch(e){R.add(n,'FAIL',String(e?.message||e));if(p&&!p.isClosed())await shot(p,'fail-'+n.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,40)).catch(()=>{})}};try{a=await E.launch({args:['.',`--user-data-dir=${d}`,'--no-sandbox']});p=await a.firstWindow();p.on('pageerror',e=>errs.push(String(e)));await p.addInitScript(()=>{localStorage.clear();localStorage.setItem('freeai.product','free');localStorage.setItem('freeai.prefs',JSON.stringify({appearance:'dark',showBottomPanel:true,approvalMode:'ask'}));localStorage.setItem('freeai.chats.free',JSON.stringify([{id:'a',title:'Linux Alpha',mode:'chat',updatedAt:2,messages:[]},{id:'b',title:'Linux Beta',mode:'chat',updatedAt:1,messages:[]}]))});await p.reload();await expect(p.locator('.desktopShell')).toBeVisible();const bw=await a.browserWindow(p);await bw.evaluate(w=>{w.setBounds({x:0,y:0,width:1440,height:900});w.show();w.focus()});await shot(p,'02-shell');
await C('Platform is Linux',async()=>{const v=await p.evaluate(()=>window.desktopApi.platform);if(v!=='linux')throw Error(v);return v});
await C('Desktop shell no Windows chrome',async()=>{if(await p.locator('.windowsDesktopRoot').count())throw Error('windowsDesktopRoot visible')});
const inv=await p.evaluate(()=>[...document.querySelectorAll('button')].filter(b=>b.offsetWidth&&b.offsetHeight).map(b=>({text:b.innerText.trim(),aria:b.getAttribute('aria-label'),title:b.title,disabled:b.disabled})));await fs.writeFile(path.join(O,'visible-buttons.json'),JSON.stringify(inv,null,2));R.add('Visible button inventory','PASS',String(inv.length));
await C('Chat Work tabs',async()=>{const c=p.getByRole('tab',{name:'Chat',exact:true}),w=p.getByRole('tab',{name:'Work',exact:true});await w.click();await expect(w).toHaveAttribute('aria-selected','true');await c.click();await expect(c).toHaveAttribute('aria-selected','true')});
await C('Sidebar hide restore',async()=>{await p.getByTitle('Hide sidebar').click();await p.getByRole('button',{name:'Open sidebar'}).click();await expect(p.locator('.gptSidebar')).toBeVisible()});
await C('Search close restores recents',async()=>{const sb=p.locator('.gptSidebar'),t=sb.getByRole('button',{name:'Search chats'}),r=sb.locator('.recentRow');await expect(r).toHaveCount(2);await t.click();await sb.getByPlaceholder('Search chats').fill('Alpha');await expect(r).toHaveCount(1);await t.click();const n=await r.count();if(n!==2)throw Error('rows='+n)});
await C('Free Super Free switch',async()=>{const t=p.getByTitle('Switch product');await t.click();await p.locator('.productMenu button').filter({hasText:'Super AI'}).click();await expect(t).toContainText('Super AI');await t.click();await p.locator('.productMenu button').filter({hasText:'Free AI'}).click()});
for(const [n,sel,ss]of[['Plugins','.desktopPrimaryNav button','03-plugins'],['Explore','.desktopPrimaryNav button','04-explore']])await C(n+' opens',async()=>{await p.locator(sel).filter({hasText:n}).click();await expect(p.locator('.contentPage')).toContainText(n);await shot(p,ss);await p.locator('.desktopPrimaryNav button').filter({hasText:'New chat'}).click()});
await C('Settings opens',async()=>{await p.locator('.profileButton').click();await p.getByText('Settings',{exact:true}).last().click();await expect(p.locator('.settingsScreen')).toBeVisible();await shot(p,'05-settings');await p.keyboard.press('Escape')});
await C('Local API chat works',async()=>{await p.evaluate(x=>window.desktopApi.addApiConnection({name:'Linux Local QA',baseUrl:x+'/v1',model:'linux-qa',apiKey:''}),u);await p.waitForTimeout(400);await p.locator('.modelButton').click();await p.getByRole('option').filter({hasText:'Linux Local QA'}).click();await p.locator('.gptComposer textarea').fill('hello');await p.getByRole('button',{name:'Send message'}).click();await expect(p.locator('.chatMessage.assistant .messageBody').last()).toHaveText('Linux local QA response',{timeout:12000});if(!qs.length)throw Error('no API request');await shot(p,'06-local-api')});
await C('Work actions',async()=>{await p.getByRole('tab',{name:'Work'}).click();const q=p.getByRole('button',{name:'Choose project'});const[f]=await Promise.all([p.waitForEvent('filechooser'),q.click()]);await f.setFiles([]);await p.getByRole('button',{name:'Plugins'}).last().click();await expect(p.locator('.contentPage')).toContainText('Plugins');await p.locator('.desktopPrimaryNav button').filter({hasText:'New chat'}).click();await p.getByRole('tab',{name:'Work'}).click()});
await C('Browser pane opens',async()=>{await p.getByRole('button',{name:'Browser'}).click();await expect(p.locator('.browserPane')).toBeVisible();await shot(p,'07-browser');await p.getByTitle('Close browser').click()});
await C('Super repository actionable',async()=>{const t=p.getByTitle('Switch product');await t.click();await p.locator('.productMenu button').filter({hasText:'Super AI'}).click();const b=p.getByRole('button',{name:'Choose repository'});await expect(b).toBeVisible();const x=await b.textContent();await b.click();await p.waitForTimeout(400);if((await b.textContent())===x)throw Error('visible no-op')});
for(const[n,fn,re]of[['Work runtime',()=>window.desktopApi.startWorkTask({provider:'x',source:'api',product:'free',prompt:'q'}),/available on Windows/i],['Computer Use',()=>window.desktopApi.computerPerformAction({action:{type:'wait',ms:1},viewport:{width:2,height:2}}),/available on Windows/i],['Dictation',()=>window.desktopApi.startSystemDictation(),/available on Windows/i],['Browser Use',()=>window.desktopApi.browserUseBuiltInAction({action:{type:'snapshot'}}),/enabled on Windows/i]])await C(n+' available',async()=>{let m='';try{await p.evaluate(fn)}catch(e){m=String(e?.message||e)}if(re.test(m))throw Error(m);return m});
R.add('Visible Dictate control',(await p.getByRole('button',{name:/Dictate/}).count())?'PASS':'FAIL');R.add('No renderer page errors',errs.length?'FAIL':'PASS',errs.join(' | '));await shot(p,'08-final')}finally{await R.save('linux-full-results.json');await fs.writeFile(path.join(O,'page-errors.json'),JSON.stringify(errs,null,2));await a?.close().catch(()=>{});s.closeAllConnections();await new Promise(r=>s.close(r));await fs.rm(d,{recursive:true,force:true}).catch(()=>{})}expect(R.r.filter(x=>x.status==='FAIL'),JSON.stringify(R.r,null,2)).toEqual([])});
