import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';

const providers=[
{id:'chatgpt',name:'ChatGPT'},{id:'claude',name:'Claude'},{id:'gemini',name:'Gemini'},{id:'deepseek',name:'DeepSeek'},{id:'grok',name:'Grok'}
];
const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=supabaseUrl&&supabaseKey?createClient(supabaseUrl,supabaseKey):null;
const isDesktop=!!window.desktopApi;
function randomKey(){const b=new Uint8Array(32);crypto.getRandomValues(b);return [...b].map(x=>x.toString(16).padStart(2,'0')).join('')}

function App(){
 const [session,setSession]=useState(null),[authMode,setAuthMode]=useState('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMessage,setAuthMessage]=useState('');
 const [provider,setProvider]=useState('chatgpt'),[prompt,setPrompt]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false);
 const [settings,setSettings]=useState(()=>({relayUrl:localStorage.getItem('relayUrl')||'',pairKey:localStorage.getItem('pairKey')||''}));
 const [status,setStatus]=useState({extension:false,relay:false});
 useEffect(()=>{if(!supabase){setSession({user:{email:'Local mode'}});return}supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!isDesktop)return;window.desktopApi.getStatus().then(setStatus);const off=window.desktopApi.onStatus(setStatus);return off},[]);
 async function authSubmit(e){e.preventDefault();setAuthMessage('');if(!supabase){setAuthMessage('Configure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to enable cloud login.');return}const {error}=authMode==='signup'?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});setAuthMessage(error?error.message:(authMode==='signup'?'Check your email if confirmation is enabled.':'Signed in.'))}
 async function googleLogin(){if(!supabase){setAuthMessage('Supabase is not configured yet.');return}await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.href}})}
 async function saveSettings(next=settings){localStorage.setItem('relayUrl',next.relayUrl);localStorage.setItem('pairKey',next.pairKey);setSettings(next);if(isDesktop)await window.desktopApi.configureRelay(next)}
 async function send(){const text=prompt.trim();if(!text||busy)return;setBusy(true);setPrompt('');setMessages(m=>[...m,{role:'user',text,provider}]);try{let answer;if(isDesktop){const r=await window.desktopApi.sendPrompt({provider,text});answer=r.text}else answer=await sendRemote(settings.relayUrl,settings.pairKey,provider,text);setMessages(m=>[...m,{role:'assistant',text:answer,provider}])}catch(e){setMessages(m=>[...m,{role:'error',text:e.message||String(e),provider}])}finally{setBusy(false)}}
 if(session===null)return <div className="center">Loading…</div>;
 if(!session)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} submit={authSubmit} google={googleLogin} message={authMessage}/>;
 return <div className="shell"><aside><div className="brand"><div className="logo">F</div><div><strong>Free AI</strong><small>All your AI, one place</small></div></div><button className="new" onClick={()=>setMessages([])}>＋ New chat</button><div className="label">Models</div>{providers.map(p=><button key={p.id} className={'model '+(provider===p.id?'active':'')} onClick={()=>setProvider(p.id)}><span>{p.name}</span><i>{isDesktop?(status.extension?'ready':'offline'):'remote'}</i></button>)}<div className="grow"/><Settings settings={settings} setSettings={setSettings} save={saveSettings} status={status}/><div className="account">{session.user?.email||'Signed in'} {supabase&&<button onClick={()=>supabase.auth.signOut()}>Sign out</button>}</div></aside><main><header><div><b>{providers.find(p=>p.id===provider)?.name}</b><span>{isDesktop?' via Chrome extension':' via paired desktop'}</span></div><div className={'dot '+(isDesktop?status.extension:(settings.pairKey?'ok':''))}/></header><section className="chat">{messages.length===0?<div className="empty"><div className="heroLogo">F</div><h1>What should the models work on?</h1><p>Select a model and send a prompt. The request is routed to the AI tab already open in Chrome.</p></div>:messages.map((m,i)=><div key={i} className={'msg '+m.role}><div className="meta">{m.role==='user'?'You':m.role==='error'?'Error':providers.find(p=>p.id===m.provider)?.name}</div><div>{m.text}</div></div>)}</section><div className="composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder={'Message '+providers.find(p=>p.id===provider)?.name+'…'}/><button disabled={busy} onClick={send}>{busy?'…':'↑'}</button></div></main></div>
}
function Auth({mode,setMode,email,setEmail,password,setPassword,submit,google,message}){return <div className="auth"><div className="authCard"><div className="heroLogo">F</div><h1>Welcome to Free AI</h1><p>Use your AI subscriptions from one clean app.</p><button className="google" onClick={google}>Continue with Google</button><div className="sep"><span/>or<span/></div><form onSubmit={submit}><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} minLength="6" required/><button className="primary">{mode==='signup'?'Create account':'Sign in'}</button></form><button className="switch" onClick={()=>setMode(mode==='signup'?'signin':'signup')}>{mode==='signup'?'Already have an account? Sign in':'No account? Create one'}</button>{message&&<p className="authMessage">{message}</p>}</div></div>}
function Settings({settings,setSettings,save,status}){const [open,setOpen]=useState(false);function generate(){const n={...settings,pairKey:randomKey()};setSettings(n);save(n)}return <div className="settings"><button className="settingsBtn" onClick={()=>setOpen(!open)}>⚙ Settings</button>{open&&<div className="panel"><label>Relay URL<input placeholder="wss://relay.example.com" value={settings.relayUrl} onChange={e=>setSettings({...settings,relayUrl:e.target.value})}/></label><label>Pairing / API key<div className="keyrow"><input value={settings.pairKey} onChange={e=>setSettings({...settings,pairKey:e.target.value})}/><button onClick={generate}>Generate</button></div></label><button className="primary" onClick={()=>save()}>Save connection</button>{isDesktop&&<small>Extension: {status.extension?'connected':'not connected'} · Relay: {status.relay?'connected':'offline'}</small>}</div>}</div>}
function sendRemote(url,key,provider,text){return new Promise((resolve,reject)=>{if(!url||!key)return reject(new Error('Set the relay URL and pairing key in Settings first.'));const ws=new WebSocket(url),id=crypto.randomUUID();const timer=setTimeout(()=>{ws.close();reject(new Error('Desktop did not answer in time.'))},120000);ws.onopen=()=>ws.send(JSON.stringify({type:'hello',role:'mobile',key}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='ready')ws.send(JSON.stringify({type:'prompt',id,provider,text}));if(m.type==='response'&&m.id===id){clearTimeout(timer);ws.close();m.error?reject(new Error(m.error)):resolve(m.text)}};ws.onerror=()=>{clearTimeout(timer);reject(new Error('Cannot connect to relay.'))}})}
createRoot(document.getElementById('root')).render(<App/>);